apiVersion: v1
kind: Namespace
metadata:
  name: cost-analysis
  labels:
    app.kubernetes.io/name: aks-cost-analysis
    azure.workload.identity/use: "true"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cost-analysis-export-sa
  namespace: cost-analysis
  labels:
    app.kubernetes.io/name: aks-cost-analysis
    app.kubernetes.io/component: cost-export
    azure.workload.identity/use: "true"
  annotations:
    azure.workload.identity/client-id: "358ab7b7-d5b4-4b67-a506-3e95a49fcac6"
    azure.workload.identity/tenant-id: "5af05be5-b9df-43d4-8897-ec17d3118935"
---
apiVersion: v1
kind: Service
metadata:
  name: cost-analysis-agent-svc
  namespace: kube-system
spec:
  selector:
    app: cost-analysis-agent
    kubernetes.azure.com/managedby: aks
  ports:
  - name: http
    protocol: TCP
    port: 9094
    targetPort: 9094
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: aks-cost-analysis-export
  namespace: cost-analysis
  labels:
    app.kubernetes.io/name: aks-cost-analysis
    app.kubernetes.io/component: cost-export
spec:
  schedule: "10 0 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            azure.workload.identity/use: "true"
        spec:
          restartPolicy: OnFailure
          serviceAccountName: cost-analysis-export-sa
          securityContext:
            runAsNonRoot: true
            runAsUser: 65534
            runAsGroup: 65534
            fsGroup: 65534
            seccompProfile:
              type: RuntimeDefault
          containers:
          - name: cost-analysis-export
            image: acrcostexportspoc.azurecr.us/aks-cost-export@sha256:5d55510c1d6571925667c8ae6cf3ebd557d11fa449d905cdf4dd2739e41b34fb
            imagePullPolicy: Always
            args:
            - export
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              runAsNonRoot: true
              runAsUser: 65534
              runAsGroup: 65534
              capabilities:
                drop:
                - ALL
            env:
            - name: COST_ANALYSIS_URL
              value: "http://cost-analysis-agent-svc.kube-system:9094"
            - name: AZURE_CLOUD
              value: "AzureGovernment"
            - name: CLUSTER_NAME
              value: "aks-backup-demo"
            - name: AZURE_STORAGE_BLOB_NAME
              value: "https://stcostexportspoc.blob.core.usgovcloudapi.net/"
            - name: AZURE_STORAGE_CONTAINER_NAME
              value: "cost-exports"
            - name: AZURE_STORAGE_AKS_DATA_PREFIX
              value: "cost-analysis/aks-backup-demo/"
            - name: AZURE_STORAGE_COST_EXPORT_PREFIX
              value: "cost-management/"
            - name: AZURE_STORAGE_RESULT_FILE
              value: "cost-analysis/result.csv"
            volumeMounts:
            - name: tmp
              mountPath: /tmp
            resources:
              requests:
                memory: "512Mi"
                cpu: "500m"
              limits:
                memory: "512Mi"
                cpu: "500m"
          volumes:
          - name: tmp
            emptyDir:
              sizeLimit: "2Gi"